# ----------------------- #
#      Main Configs       #
# ----------------------- #

url: https://wayinone.github.io/
title: Weiying Wang Personal page
email: wei-ying_wang@brown.edu
author: Weiying Wang
description: > # This is Weiying's Personal website. I display some of my works here. I worked on image compression and data clustering problems.

copyright: 'Copyright &copy; 2017 Weiying Wang. All Rights Reserved.'

# ----------------------- #
#    Jekyll & Plugins     #
# ----------------------- #

# Build settings
markdown: kramdown
permalink: pretty
highlighter: rouge

# ----------------------- #
#   3rd Party Settings    #
# ----------------------- #

social:
  - title: linkedin
    url: https://www.linkedin.com/in/wayin1/
